# url=jdbc:postgresql://localhost:5432/mydb
# username=postgres
# password=postgres


# driver=org.postgresql.Driver
# changeLogFile=database/db.changelog-master.xml
# classpath=C:/Users/731663/Downloads/postgresql-42.7.11.jar

changeLogFile=database/db.changelog-master.xml

url=${DB_URL}
username=${DB_USERNAME}
password=${DB_PASSWORD}

driver=org.postgresql.Driver