name: Database Migration

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  migrate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Liquibase Update
        uses: liquibase-github-actions/update@v4.29.1
        with:
          changelogFile: database/db.changelog-master.xml   # <-- adjust this path
          url: ${{ secrets.DEV_DB_URL }}
          username: ${{ secrets.DEV_DB_USERNAME }}
          password: ${{ secrets.DEV_DB_PASSWORD }}
          classpath: "."
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
